# Generated by Django 5.1.2 on 2024-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_fk_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('administracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'administracion',
            },
        ),
    ]
