# Generated by Django 5.1.2 on 2024-11-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('estatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estatus',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('precio_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(max_length=7)),
            ],
            options={
                'db_table': 'precio',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=150)),
                ('respuesta', models.CharField(max_length=150)),
                ('fk_usuarios', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
    ]
