# Generated by Django 5.1.2 on 2024-11-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_estatus_precio_preguntas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administracion',
            old_name='usuario',
            new_name='usuario_administracion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='localidad',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
