# Generated by Django 5.1.2 on 2024-11-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_usuario_administracion_usuario_administracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracion',
            name='password',
        ),
        migrations.AddField(
            model_name='administracion',
            name='correo_administracion',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='administracion',
            name='password_administracion',
            field=models.CharField(default='default_password', max_length=20),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='correo_usuario',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password_usuario',
            field=models.CharField(default='default_password', max_length=20),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='usuario_administracion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('mueble_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('medidas', models.CharField(max_length=30)),
                ('fk_categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_precio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.precio')),
                ('fk_pregunta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
            ],
            options={
                'db_table': 'mueble',
            },
        ),
    ]
