# Generated by Django 5.1.2 on 2024-11-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_administracion_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comprador', models.CharField(max_length=255)),
                ('telefono', models.BigIntegerField(max_length=13)),
                ('detalles', models.CharField(max_length=255)),
                ('fk_estatus', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.estatus')),
                ('fk_mueble', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.mueble')),
                ('fk_precio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.precio')),
                ('fk_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
    ]
