# Generated by Django 5.1.2 on 2024-11-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='telefono',
        ),
    ]
